#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

## Set GTK Themes, Icons, Cursor and Fonts

THEME='Tokyonight-Dark-B'
ICONS='Material-Palenight'
FONT='Maple Mono SC NF'
# CURSOR='Afterglow-Recolored-Catppuccin-Blue-v2'
# CUROSO_SIZE='32'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes() {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	# ${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
	# ${SCHEMA} cursor-size "$CUROSO_SIZE"
}

apply_themes
