decoration{
    rounding = 3

    active_opacity = 1.0
    inactive_opacity = 0.9

    drop_shadow = true
    shadow_range = 20
    shadow_offset = [1, 2]
    col.shadow = 0x33000000
    col.shadow_inactive = 0x22000000

    blur{
        enabled = true
        xray = true
        ignore_opacity = true
    }
}