bind = $MOD,E,exec,nemo
bind = $MOD,Q,exec,kitty
bind = $MOD,S,exec,kitty btop
bind = $MOD,N,exec,~/.config/hypr/scripts/toggle/waydroid
bind = $MOD,M,exec,vmware -X ~/vmware/Windows\ 10/Windows\ 10.vmx
