bind = ,XF86AudioRaisevolume,exec,amixer -q -D pulse sset Master 5%+ unmute
bind = ,XF86AudioLowervolume,exec,amixer -q -D pulse sset Master 5%- unmute
bind = ,XF86AudioMute,exec,amixer -q -D pulse sset Master toggle